<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Segoe UI', sans-serif;
            font-size: 14px;
            color: #333;
            line-height: 1.6;
            margin: 40px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #ccc;
            margin-bottom: 30px;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 28px;
            color: #2c3e50;
        }
        .header p {
            margin: 5px 0;
            color: #7f8c8d;
        }

        .section {
            margin-bottom: 40px;
        }

        h2 {
            color: #2980b9;
            border-left: 6px solid #3498db;
            padding-left: 10px;
            margin-bottom: 10px;
            font-size: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #f0f4f8;
            font-weight: bold;
            color: #2c3e50;
        }

        tr:nth-child(even) {
            background-color: #fafafa;
        }

        .highlight {
            font-weight: bold;
            color: #16a085;
        }

        .footer {
            position: fixed;
            bottom: 20px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 12px;
            color: #999;
        }

    </style>
</head>
<body>

@if($noRecordsAvailable)
    <p>No records available for the selected date range.</p>
@else

    <div class="header">
        <h1>{{ $title }}</h1>
        <p>{{ $content }}</p>

        <p>Report Generated by: {{ auth()->user()->name }}</p>
        <p><small>Generated on {{ now()->format('F j, Y') }}</small></p>
    </div>

    <div class="section">
        <h2>Child Health Monitoring</h2>
        <p>Total Children Monitored: <span class="highlight">{{ $childMonitor }}</span></p>
        <p>Children with Improved BMI: <span class="highlight">{{ $improvedCount }}</span></p>
        <p>Good Nutrition Count (BMI > 18.5): <span class="highlight">{{ $goodNutritionCount }}</span></p>
        <p>Children Needing Support (BMI < 18.5): <span class="highlight">{{ $needSupportCount }}</span></p>
        <p>Average BMI: <span class="highlight">{{ number_format($averageBmi, 2) }}</span></p>
    </div>

    <div class="section">
        <h2>Financial Summary</h2>
        <p>Total Funds Received: <span class="highlight">${{ number_format($totalFunds, 2) }}</span></p>
        <p>Total Expenses: <span class="highlight">${{ number_format($totalExpenses, 2) }}</span></p>
    </div>

    @if ($expenses->count())
        <div class="section">
            <h2>Expense Details</h2>
            <table>
                <thead>
                <tr>
                    <th>Description</th>
                    <th>Amount</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($expenses as $expense)
                    <tr>
                        <td>{{ $expense->purpose }}</td>
                        <td>${{ number_format($expense->amount, 2) }}</td>
                        <td>{{ \Carbon\Carbon::parse($expense->created_at)->toFormattedDateString() }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    @endif

    <div class="section">
        <h2>Top Sponsors – Cash</h2>
        <table>
            <thead>
            <tr>
                <th>Sponsor Name</th>
                <th>Total Funds</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($topFundsSponsors as $sponsor)
                <tr>
                    <td>{{ $sponsor->name }}</td>
                    <td>${{ number_format($sponsor->total_amount, 2) }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Top Sponsors – Goods</h2>
        <table>
            <thead>
            <tr>
                <th>Sponsor Name</th>
                <th>Estimated Goods Value</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($topGoodsSponsors as $sponsor)
                <tr>
                    <td>{{ $sponsor->name }}</td>
                    <td>${{ number_format($sponsor->total_amount, 2) }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Coverage Summary</h2>
        <p>Total Locations Reached: <span class="highlight">{{ $addresses }}</span></p>
    </div>

    <div class="footer">
        © {{ \Carbon\Carbon::now()->year }} Nutrisafari. All rights reserved.    </div>

@endif

</body>
</html>
